version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: hexo-theme-minidyne
    versions:
    - 3.2.4
  - dependency-name: hexo
    versions:
    - 5.4.0
  - dependency-name: markdownlint
    versions:
    - 0.23.0
