language: node_js
node_js:
- node
git:
  depth: 2
branches:
  only:
  - master
install:
- npm install
script:
- npm run generateTravis
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: G9Aj6iAMpDMwWPVzXwHhmfsW23ea6rYH6hNIkGpkzuOs/Y31Fa2s0vPhHW5pCTUk5Voo38qUfjb5Lx4DCqxsLfYDwdYsaXZHwMKSWjmWIfgqi4TuOTii6E00Ad3ZCHs/ZfulQzljQYgtertoQsv0UQOvrdcGi+Cc8QtnO40qB9jDLiDEmXJysHtGFnID7DJaFN1BQ53s3Qn0dyja0UZkS/Wsw4rJl/4I4BC2p/mHRM+O3mTr/bFs2knNMGo3K7BSH77ObJnuMxU/qQK+OlVkb2cT0RmAI9z7CrNIcZUFigPzKkQoS/ESvl+66Hl1e9/dVw4CX0N4aT5ScSJ3SxkBKtDURXP5PjOzADAD+k1OK7p3l3Ofj5aNqyRE7P/qSvQOgzYQx9mGVhXCOVYaDZsKgFQzQz2W+99PqJSkva6qDitE5Ry7Or/bUZpCKy40AzVJY2X02cPpG0MWGcGrp09XFzXUVR0g9YkHJMKeNdUWVYcxk4RBnKBVg3ozPgWRaq9fPnWc7WKrLvOwJIdsWuHiAGw0HfVONFYoaXRIV+gw0y35IQoY7SN0ya4Xg//uO0Hts6Qk9oH8tdeJUIufT4JnvWbUXiGkcK4vdJ1h7s0BDr3WUcApWzU+LoM4E24dmQLlCk7CyyoRISkQp1riDgdKCYYJ/ZXJvgx9p2tvYUQ+Pvg=
