language: node_js
node_js:
- node
branches:
  only:
  - master
before_install:
- npm install -g hexo
install:
- npm install
script:
- >-
  hexo generate
  
  "find public -type f -print0 | xarg -n 1 -I {} curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp.cluster014.hosting.ovh.net/www/test2{}"
env:
  global:
  - FTP_USER=xntprja
  - secure: ivM4P5Y3gxWgYcW2IN9nZ+FIqcX0UDgXvD6I4cauvHCkIB8sjy2gh6lYKtncCT64KkLMaYiA7BpvO/+P32kgtjj7CuzBF9XoJ41hJNsmg3P08R1/d++DXZf/+pZn8t1OhFH39RjBUtltOroXPgQDnBRVl1M3KVvv3VpHoy88D16zROVQY+oH6azvfqjYbeCnH77ckrYwcbbsXCOZ/+Ju0jLf3B9Af4D8saaJGUjT2m8Md51agu+2LaRDkg95E7QfWoPIbWdZXz6u8Wzny0xYwr/zGDELlOC7UAaKGplO89qF2ra+dR9xTtwcUYNjQZibCEiq5xAoPjz2cwy3tWcjtvNUAM/u8M/6hS83iJ37pxnr56Bgk1fls6bbMo5FZMUCG/0xxD9SbGQABbnOstk0qW4l3JO8O9dakEuVV9XRrt+UO4jgL6RgyUbr5FIvs/sRPQgjY6253JJ5w41evNKf2aGEzQXz1nISeVijdUGwAf/cYCZOky36D2KeKuXnIlfWafogtlS5w/fZSW/2OMraHBWcp8TbACgbop+Tq+3Ws+1YbyjK5/3svmz+hsqfmLhbJRR9TRq/bt7xidLiuPRpwXGMGLKDZtSICY6Iyb/6u2kaKdeIAU2PLcai6VJRRgMnq93G1CXKRoUfD8asoK5gIUDJ9aCPqGnXRtWH2HMqbpU=
