# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Thomas Piart - tpî.eu
author: Thomas Piart
description: Thomas Piart - tpî.eu - Personal site
language: en

# URL
url: https://tpî.eu
root: /

# Directory
skip_render:
 - 'assets/404.html'
 - 'googlec312aa49c107e0a6.html'

include:
  - .htaccess

# Writing
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Pagination
per_page: 0

# Extensions
## Plugins: https://hexo.io/plugins/
flickr_api_key: 78501c2c12bff9c7a22c013d5155045a

## Themes: https://hexo.io/themes/
theme: minidyne

menu:
  Home: /
  Resume: /resume/

uncss:
  priority : 12

html_minifier:
  removeComments: true
  collapseWhitespace: true
  collapseBooleanAttributes: true
  removeEmptyAttributes: true
  removeStyleLinkTypeAttributes: true

markdown_lint:
  default: true
  files: "{Readme.md,source/**/*.md,scafolds/*.md,themes/**/*.md}"
  MD013:
    line_length: 372
    code_block_line_length: 830
  MD024: 0
  MD034: 0
