# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Thomas Piart - tpî.eu
author: Thomas Piart
language: en

# URL
url: https://tpî.eu
root: /

# Directory
skip_render:
 - 'assets/404.html'
 - 'googlec312aa49c107e0a6.html'

include:
  - .htaccess

# Writing
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Pagination
per_page: 5

# Extensions
## Plugins: https://hexo.io/plugins/

flickr_api_key: 78501c2c12bff9c7a22c013d5155045a
## Themes: https://hexo.io/themes/
theme: minidyne

menu:
  Home: /
  Archives: /archives/
  Resume: /resume/

hfc_favicons:
  enable: false

uncss:
  priority : 12
