# Hexo Configuration

# Site
title: Thomas Piart - tpî.eu
author: Thomas Piart
description: Thomas Piart - tpî.eu - Personal site

# URL
url: https://tpî.eu

# Directory
skip_render:
 - 'assets/404.html'

# Writing
highlight:
  line_number: false
  tab_replace:

# Pagination
per_page: 0

# dates
timezone: 'UTC'
use_date_for_updated: true

## Themes:
theme: minidyne

menu:
  Home: /
  Resume: /resume/

## Plugins:
flickr_api_key: 78501c2c12bff9c7a22c013d5155045a

marked:
  headerIds: false

feed:
  type:
    - atom
    - rss2

uncss:
  priority: 12

html_minifier:
  decodeEntities: true
  
markdown_lint:
  default: true
  files: "{Readme.md,source/**/*.md,scafolds/*.md,themes/**/*.md}"
  MD013:
    line_length: 372
    code_block_line_length: 830
  MD024: 0
  MD034: 0
