version: 1.1.{build}
install:
- ps: Install-Product node 'Stable'
build_script:
- cmd: >-
    npm i
    
    npx hexo g

    copy indexing\robots.txt public\robots.txt
    
test: off
before_deploy:
- ps: $root = Resolve-Path .\public; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName www }
deploy:
- provider: FTP
  host: ftp.cluster014.ovh.net
  protocol: ftp
  username: xntprja
  password:
    secure: LjMgHtV+ERLAzq3CuesEh6b2cMEorfg9O+EYs+/I0+M=
  folder: /www
  artifact: www
  active_mode: false
  beta: true
  debug: false
  on:
      branch: master