version: 1.1.{build}
install:
- ps: Install-Product node 'Stable'
build_script:
- cmd: >-
    npm install

    npm -g install hexo-cli
    
    hexo generate

test: off
before_deploy:
- ps: $root = Resolve-Path .\public; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName www }
deploy:
- provider: FTP
  host: ftp.cluster014.hosting.ovh.net
  protocol: ftp
  username: xntprja
  password:
    secure: Z4qtNeq80Mfc805WuSF9Pz0FQkxg2lpB10iP9xbU4cw=
  folder: /www
  artifact: www
  active_mode: false
  beta: true
  debug: false