name: deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm i
    - run: npx hexo g
    - uses: actions/upload-artifact@master
      with:
        path: public
        name: public
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'master'
    steps:
      - run: set FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: public
      - run: npm i -g firebase-tools
      - run: firebase deploy
    
